import type { Metadata } from "next";

import { poppins, roboto } from "@/lib/fonts";

import "./globals.css";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Store",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${roboto.variable} font-roboto subpixel-antialiased`}
      suppressHydrationWarning
    >
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
